ti-ipc: suppress gcc10 multiple definitions of _GateHWSpinlock_cfgParams
Workaround for this gcc10 error:
.../linux/src/api/gates/GateHWSpinlock.c:96: multiple definition of `_GateHWSpinlock_cfgParams';
.libs/Ipc.o:.../linux/src/api/Ipc.c:97: first defined here

Needs to be resolved properly in the code:
https://gcc.gnu.org/gcc-10/porting_to.html

Signed-off-by: Denys Dmytriyenko <denys@konsulko.com>
Cc: Suman Anna <s-anna@ti.com>