vshmem-uio-driver: Make it ti-soc specific
It rdepends on jailhouse package which is already marked at ti-soc
compatible only, so in a multi-BSP setup it ends up breaking builds

ERROR: Nothing RPROVIDES 'jailhouse' (but
/home/jenkins/oe/world/yoe/sources/meta-ti/recipes-bsp/ivshmem-uio/ivshmem-uio-driver_git.bb
RDEPENDS on or otherwise requires it)
jailhouse was skipped: incompatible with machine qemux86-64 (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'jailhouse' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jailhouse']
NOTE: Runtime target 'ivshmem-uio-driver-dev' is unbuildable,
removing...
Missing or unbuildable dependency chain was: ['ivshmem-uio-driver-dev', 'jailhouse']
ERROR: Nothing RPROVIDES 'ivshmem-uio-driver' (but /home/jenkins/oe/world/yoe/sources/meta-ti/recipes-bsp/ivshmem-uio/ivshmem-uio-driver_git.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ivshmem-uio-driver'
NOTE: Runtime target 'ivshmem-uio-driver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ivshmem-uio-driver']

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Denys Dmytriyenko <denys@ti.com>