meta-ti-bsp: Update mesa bbappend files for mesa-23
The mesa recipes in oe-core have been updated to mesa-23 causing the
following build error:

    $ bitbake core-image-minimal
    Loading cache: 100% |                                               | ETA:  --:--:--
    Loaded 0 entries from dependency cache.
    Parsing recipes: 100% |#############################################| Time: 0:00:20
    Parsing of 2816 .bb files complete (0 cached, 2816 parsed). 4472 targets, 484 skipped, 0 masked, 0 errors.
    ERROR: No recipes in default available for:
      /build/../oe/meta-ti/meta-ti-bsp/recipes-graphics/mesa/mesa-gl_22.%.bbappend
      /build/../oe/meta-ti/meta-ti-bsp/recipes-graphics/mesa/mesa_22.%.bbappend

    Summary: There was 1 ERROR message, returning a non-zero exit code.

Signed-off-by: Theodore A. Roth <troth@openavr.org>
Signed-off-by: Theodore A. Roth <theodore_roth@trimble.com>
Reviewed-by: Denys Dmytriyenko <denys@konsulko.com>
Signed-off-by: Ryan Eatmon <reatmon@ti.com>