remaining recipes: fix build issue due to bb.data.* deprecation
Causes following error:
Exception: AttributeError: module 'bb.data' has no attribute 'getVar'

Signed-off-by: Denys Dmytriyenko <denys@ti.com>