vis: suppress "ldflags" QA error
It is a pre-built binary, hence no control over passing correct LDFLAGS.
This used to be a warning and recently became an error. Fixes:
ERROR: vis-01.50.07.15-r1 do_package_qa: QA Issue: File /usr/bin/RadioApp in package vis doesn't have GNU_HASH (didn't pass LDFLAGS?) [ldflags]

Signed-off-by: Denys Dmytriyenko <denys@konsulko.com>