am33x-cm3: Add TOOLCHAIN_OPTIONS to redefined CC
This error will show up when using sstate which was generated
using a different buiid time sysroot. Since we override CC we
still need to honor --sysroot which is specified via TOOLCHAIN_OPTIONS

Fixes

| DEBUG: Executing shell function do_compile
|      CC       src/sys_exec/sys_init.o
| In file included from src/sys_exec/rsc_table.h:13:0,
|                  from src/sys_exec/sys_init.c:19:
|
/home/ubuntu/work/angstrom/build/tmp-angstrom_next-glibc/sysroots/x86_64-linux/usr/lib/arm-angstrom-linux-gnueabi/gcc/arm-angstrom-linux-gnueabi/4.9.2/include/stdint.h:9:26:
fatal error: stdint.h: No such file or directory
|  # include_next <stdint.h>
|                           ^
| compilation terminated.
| make: *** [src/sys_exec/sys_init.o] Error 1

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Denys Dmytriyenko <denys@ti.com>