mesa-pvr: correct INSANE_SKIP for mesa-megadriver
In the original file this was copied from, $PN == mesa. But in this
context, $PN == mesa-pvr, while the PACKAGES and FILES logic still
explicitly refers to the mesa-megadriver package. Hence the build
fails

ERROR: mesa-pvr-2_25.2.8-r1 do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package mesa-megadriver contains symlink .so '/usr/lib/dri/swrast_dri.so' [dev-so]
ERROR: mesa-pvr-2_25.2.8-r1 do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package mesa-megadriver contains symlink .so '/usr/lib/dri/virtio_gpu_dri.so' [dev-so]
ERROR: mesa-pvr-2_25.2.8-r1 do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package mesa-megadriver contains symlink .so '/usr/lib/dri/kms_swrast_dri.so' [dev-so]
ERROR: mesa-pvr-2_25.2.8-r1 do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package mesa-megadriver contains symlink .so '/usr/lib/dri/zink_dri.so' [dev-so]
ERROR: mesa-pvr-2_25.2.8-r1 do_package_qa: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: [...]/mesa-pvr/25.2.8/temp/log.do_package_qa.3911784
ERROR: Task ([...]/meta-ti/meta-ti-bsp/recipes-graphics/mesa/mesa-pvr_25.2.8.bb:do_package_qa) failed with exit code '1'

Spell the package override correctly for the INSANE_SKIP suppression
to have effect.

Signed-off-by: Rasmus Villemoes <ravi@prevas.dk>
Signed-off-by: Ryan Eatmon <reatmon@ti.com>