gdbc6x: suppress gcc10 multiple definitions of *_varobj_ops
Workaround for the following gcc10 errors:
.../gdbc6x/gdb/varobj.h:221: multiple definition of `ada_varobj_ops'; mi-cmd-var.o:.../gdbc6x/gdb/./varobj.h:221: first defined here
.../gdbc6x/gdb/varobj.h:220: multiple definition of `java_varobj_ops'; mi-cmd-var.o:.../gdbc6x/gdb/./varobj.h:220: first defined here
.../gdbc6x/gdb/varobj.h:219: multiple definition of `cplus_varobj_ops'; mi-cmd-var.o:.../gdbc6x/gdb/./varobj.h:219: first defined here
.../gdbc6x/gdb/varobj.h:218: multiple definition of `c_varobj_ops'; mi-cmd-var.o:.../gdbc6x/gdb/./varobj.h:218: first defined here

Needs to be resolved properly in the code later:
https://gcc.gnu.org/gcc-10/porting_to.html

Signed-off-by: Denys Dmytriyenko <denys@konsulko.com>