gcc-arm-baremetal: Add arch to INSANE_SKIP
A newly enabled check in master is causing errors with this package:

ERROR: QA Issue: Architecture did not match (ARM, expected x86-64)

Adding arch to the INSANE_SKIP variable disables that check for this
recipe.

Suggested-by: Denys Dmytriyenko <denys@konsulko.com>
Signed-off-by: Ryan Eatmon <reatmon@ti.com>