debugss-module-drv: Fix compile failure under kernel v6.10
A compile error has apperaed when building againt the v6.10 kernel.

git/debugss_module/debugss-mod/debugss_kmodule.c:1149:34: error: array type has incomplete element type 'struct of_device_id'
 1149 | static const struct of_device_id dra7xx_debugss_of_match[] = {
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~

The easy fix is just to add an include for the header that defines the
missing struct.

Signed-off-by: Ryan Eatmon <reatmon@ti.com>