ti-librpmsg-dma: mark it as compatible with K3 platforms
As ti-librpmsg-dma depends on ti-rpmsg-char, which is only compatible
with K3 platforms, ti-librpmsg-dma should also have the same limitations.

This resolves yocto-check-layer failure:

ERROR: Nothing PROVIDES 'ti-rpmsg-char' (but .../ti-librpmsg-dma_1.0.bb DEPENDS on or otherwise requires it)
ti-rpmsg-char was skipped: incompatible with machine qemux86-64 (not in COMPATIBLE_MACHINE)

Signed-off-by: Denys Dmytriyenko <denys@konsulko.com>
Signed-off-by: Ryan Eatmon <reatmon@ti.com>