{qmss, cppi, srio, pa, sa}-lld-test: suppress gcc10 multiple definition of fw_qmss*
Workaround for these:
.../ti/drv/cppi/test/k2h/armv7/linux/fw_main.c:50: multiple definition of `coreNum';
./obj/k2h/cppi/test/cppi_test.o:.../ti/drv/cppi/test/src/cppi_test.c:102: first defined here
.../ti/drv/cppi/test/k2h/armv7/linux/fw_main.c:50: multiple definition of `errorCount';
./obj/k2h/cppi/test/cppi_test.o:.../ti/drv/cppi/test/src/cppi_test.c:102: first defined here
.../ti/drv/cppi/test/k2h/armv7/linux/fw_test.h:85: multiple definition of `fw_passCfgVaddr';
./obj/k2h/cppi/test/cppi_test.o:.../ti/drv/cppi/test/k2h/armv7/linux/fw_test.h:85: first defined here
.../ti/drv/cppi/test/k2h/armv7/linux/fw_test.h:84: multiple definition of `fw_srioCfgVaddr';
./obj/k2h/cppi/test/cppi_test.o:.../ti/drv/cppi/test/k2h/armv7/linux/fw_test.h:84: first defined here
.../ti/drv/cppi/test/k2h/armv7/linux/fw_test.h:83: multiple definition of `fw_qmssDataVaddr';
./obj/k2h/cppi/test/cppi_test.o:.../ti/drv/cppi/test/k2h/armv7/linux/fw_test.h:83: first defined here
.../ti/drv/cppi/test/k2h/armv7/linux/fw_test.h:82: multiple definition of `fw_qmssCfgVaddr';
./obj/k2h/cppi/test/cppi_test.o:.../ti/drv/cppi/test/k2h/armv7/linux/fw_test.h:82: first defined here

Needs to be fixed properly later:
https://gcc.gnu.org/gcc-10/porting_to.html

Signed-off-by: Denys Dmytriyenko <denys@konsulko.com>