Fix "basehash value changed" errors and BB_NUMBER_THREADS usage
Changing BB_NUMBER_THREADS between successive builds causes a "basehash
value changed" error. Additionally, using BB_NUMBER_THREADS to pass a
number of processes to run to xdc is wrong: PARALLEL_MAKE is the correct
variable to use.

Fix both problems by using oe.utils.parallel_make_argument() to obtain the
number of processes to run from PARALLEL_MAKE.

Fixes:

  ERROR: When reparsing .../meta-ti/recipes-ti/ipc/ti-ipc-rtos_git.bb.do_configure, the basehash value changed from 63897a188012cedde03f756b5dbbfa70 to 13b80bf4f4327c367bd201eb4aa32ad7. The metadata is not deterministic and this needs to be fixed.
  ERROR: When reparsing .../meta-ti/recipes-ti/ipc/ti-ipc-rtos_git.bb.do_compile, the basehash value changed from 2fb59a7db2a2f69d2c25c06c1b6a4245 to 314c664cc040afae2800fcc378dd9ae0. The metadata is not deterministic and this needs to be fixed.

Steps to reproduce:

  BB_NUMBER_THREADS="3" bitbake ti-ipc-rtos ti-ipc-examples-linux
  BB_NUMBER_THREADS="4" bitbake -c cleansstate osal-rtos
  BB_NUMBER_THREADS="5" bitbake ti-ipc-rtos ti-ipc-examples-linux

Reported here: https://e2e.ti.com/support/processors/f/791/p/825142/3059419
Reported-by: Matthew McKee (e-mail unknown)
Suggested-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Luca Ceresoli <luca@lucaceresoli.net>
Signed-off-by: Denys Dmytriyenko <denys@ti.com>